name: BuildUSDClone

on:
  workflow_dispatch:

jobs:
  GetUser:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    outputs:
      require-result: ${{ steps.check.outputs.require-result }}
      check-result: ${{ steps.check.outputs.check-result }}
      user-permission: ${{ steps.check.outputs.user-permission }}
    steps:
      - name: CheckPermissions
        uses: actions-cool/check-user-permission@v2
        id: UserPermission
        with:
          require: 'write'
          username: ${{ github.triggering_actor }}
      - name: PrintPermissions
        run: |
          echo "The user: ${{ github.triggering_actor }}"
          echo "The permissions: ${{ steps.check.outputs.user-permission }}"
